# travis.yml
language: python
dist: xenial
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - python -m spacy download en_core_web_md
  - sh bootstrap.sh
script:
  - MPLBACKEND=agg pytest test.py
